type RowType = {
    keys: Array<{ key: string, code: number | string }>;
    styles: string
}

export const englKeyboard: Array<RowType[]> = [
    [
        { keys: [
            { key: '1', code: 49 },
            { key: '2', code: 50 },
            { key: '3', code: 51 },
            { key: '4', code: 52 },
            { key: '5', code: 53 },
            { key: '6', code: 54 },
            { key: '7', code: 55 },
            { key: '8', code: 56 },
            { key: '9', code: 57 },
            { key: '0', code: 48 },
        ], styles: '',
        },
        { keys: [
            { key: 'q', code: 'KeyQ' },
            { key: 'w', code: 'KeyW' },
            { key: 'e', code: 'KeyE' },
            { key: 'r', code: 'KeyR' },
            { key: 't', code: 'KeyT' },
            { key: 'y', code: 'KeyY' },
            { key: 'u', code: 'KeyU' },
            { key: 'i', code: 'KeyI' },
            { key: 'o', code: 'KeyO' },
            { key: 'p', code: 'KeyP' },
        ],
        styles: '',
        },
        { keys: [
            { key: 'a', code: 'KeyA' },
            { key: 's', code: 'KeyS' },
            { key: 'd', code: 'KeyD' },
            { key: 'f', code: 'KeyF' },
            { key: 'g', code: 'KeyG' },
            { key: 'h', code: 'KeyH' },
            { key: 'j', code: 'KeyJ' },
            { key: 'k', code: 'KeyK' },
            { key: 'l', code: 'KeyL' },
        ],
        styles: 'repeat(9, 1fr)',
        },
        { keys: [
            { key: 'Shift', code: 'ShiftLeft' },
            { key: 'z', code: 'KeyZ' },
            { key: 'x', code: 'KeyX' },
            { key: 'c', code: 'KeyC' },
            { key: 'v', code: 'KeyV' },
            { key: 'b', code: 'KeyB' },
            { key: 'n', code: 'KeyN' },
            { key: 'm', code: 'KeyM' },
            { key: 'Backspace', code: 'Backspace' },
        ],
        styles: 'repeat(9, 1fr)',
        },
        { keys: [
            { key: ',', code: 'NumpadDecimal' },
            { key: 'Ru', code: 190454634 },
            { key: 'Space', code: 'Space' },
            { key: '.', code: 'Period' },
            { key: 'Enter', code: 'Enter' },
        ],
        styles: '1.20fr 1.3fr 4fr 1.20fr 1.3fr',
        },
    ],
    [
        { keys: [
            { key: '1', code: 49 },
            { key: '2', code: 50 },
            { key: '3', code: 51 },
            { key: '4', code: 52 },
            { key: '5', code: 53 },
            { key: '6', code: 54 },
            { key: '7', code: 55 },
            { key: '8', code: 56 },
            { key: '9', code: 57 },
            { key: '0', code: 48 },
        ],
        styles: '',
        },
        { keys: [
            { key: 'Q', code: 'KeyQ' },
            { key: 'W', code: 'KeyW' },
            { key: 'E', code: 'KeyE' },
            { key: 'R', code: 'KeyR' },
            { key: 'T', code: 'KeyT' },
            { key: 'Y', code: 'KeyY' },
            { key: 'U', code: 'KeyU' },
            { key: 'I', code: 'KeyI' },
            { key: 'O', code: 'KeyO' },
            { key: 'P', code: 'KeyP' },
        ],
        styles: '',
        },
        { keys: [
            { key: 'A', code: 'KeyA' },
            { key: 'S', code: 'KeyS' },
            { key: 'D', code: 'KeyD' },
            { key: 'F', code: 'KeyF' },
            { key: 'G', code: 'KeyG' },
            { key: 'H', code: 'KeyH' },
            { key: 'J', code: 'KeyJ' },
            { key: 'K', code: 'KeyK' },
            { key: 'L', code: 'KeyL' },
        ],
        styles: 'repeat(9, 1fr)',
        },
        { keys: [
            { key: 'Shift', code: 'ShiftLeft' },
            { key: 'Z', code: 'KeyZ' },
            { key: 'X', code: 'KeyX' },
            { key: 'C', code: 'KeyC' },
            { key: 'V', code: 'KeyV' },
            { key: 'B', code: 'KeyB' },
            { key: 'N', code: 'KeyN' },
            { key: 'M', code: 'KeyM' },
            { key: 'Backspace', code: 'Backspace' },
        ],
        styles: 'repeat(9, 1fr)',
        },
        { keys: [
            { key: ',', code: 'NumpadDecimal' },
            { key: 'Ru', code: 190454634 },
            { key: 'Space', code: 'Space' },
            { key: '.', code: 'Period' },
            { key: 'Enter', code: 'Enter' },
        ],
        styles: '1.20fr 1.3fr 4fr 1.20fr 1.3fr',
        },
    ],
];

export const ruKeyboard: Array<RowType[]> = [
    [
        {
            keys: [
                { key: '1', code: 49 },
                { key: '2', code: 50 },
                { key: '3', code: 51 },
                { key: '4', code: 52 },
                { key: '5', code: 53 },
                { key: '6', code: 54 },
                { key: '7', code: 55 },
                { key: '8', code: 56 },
                { key: '9', code: 57 },
                { key: '0', code: 48 },
            ],
            styles: 'repeat(10, 1fr)',
        },
        {
            keys: [
                { key: 'й', code: 'KeyY' },
                { key: 'ц', code: 'KeyW' },
                { key: 'у', code: 'KeyU' },
                { key: 'к', code: 'KeyK' },
                { key: 'е', code: 'KeyE' },
                { key: 'н', code: 'KeyN' },
                { key: 'г', code: 'KeyG' },
                { key: 'ш', code: 'KeyI' },
                { key: 'щ', code: 'KeyO' },
                { key: 'з', code: 'KeyZ' },
                { key: 'х', code: 'BracketLeft' },
                { key: 'ъ', code: 'BracketRight' },
            ],
            styles: 'repeat(12, 1fr)',
        },
        {
            keys: [
                { key: 'ф', code: 'KeyF' },
                { key: 'ы', code: 'KeyY' },
                { key: 'в', code: 'KeyV' },
                { key: 'а', code: 'KeyA' },
                { key: 'п', code: 'KeyP' },
                { key: 'р', code: 'KeyR' },
                { key: 'о', code: 'KeyO' },
                { key: 'л', code: 'KeyL' },
                { key: 'д', code: 'KeyD' },
                { key: 'ж', code: 'Semicolon' },
                { key: 'э', code: 'KeyE' },
            ],
            styles: 'repeat(11, 1fr)',
        },
        {
            keys: [
                { key: 'Shift', code: 'ShiftLeft' },
                { key: 'я', code: 'KeyZ' },
                { key: 'ч', code: 'KeyX' },
                { key: 'с', code: 'KeyS' },
                { key: 'м', code: 'KeyM' },
                { key: 'и', code: 'KeyI' },
                { key: 'т', code: 'KeyT' },
                { key: 'ь', code: 'KeyM' },
                { key: 'б', code: 'KeyB' },
                { key: 'ю', code: 'Period' },
                { key: 'Backspace', code: 'Backspace' },
            ],
            styles: 'repeat(11, 1fr)' },
        {
            keys: [
                { key: ',', code: 'NumpadDecimal' },
                { key: 'En', code: 190454634 },
                { key: 'Space', code: 'Space' },
                { key: '.', code: 'Period' },
                { key: 'Enter', code: 'Enter' },
            ],
            styles: '1.20fr 1.3fr 4fr 1.20fr 1.3fr' },
    ],
    [
        {
            keys: [
                { key: '1', code: 49 },
                { key: '2', code: 50 },
                { key: '3', code: 51 },
                { key: '4', code: 52 },
                { key: '5', code: 53 },
                { key: '6', code: 54 },
                { key: '7', code: 55 },
                { key: '8', code: 56 },
                { key: '9', code: 57 },
                { key: '0', code: 48 },
            ], styles: 'repeat(10, 1fr)',
        },
        {
            keys: [
                { key: 'Й', code: 'KeyY' },
                { key: 'Ц', code: 'KeyW' },
                { key: 'У', code: 'KeyU' },
                { key: 'К', code: 'KeyK' },
                { key: 'Е', code: 'KeyE' },
                { key: 'Н', code: 'KeyN' },
                { key: 'Г', code: 'KeyG' },
                { key: 'Ш', code: 'KeyI' },
                { key: 'Щ', code: 'KeyO' },
                { key: 'З', code: 'KeyZ' },
                { key: 'Х', code: 'BracketLeft' },
                { key: 'Ъ', code: 'BracketRight' },
            ],
            styles: 'repeat(12, 1fr)',
        },
        {
            keys: [
                { key: 'Ф', code: 'KeyF' },
                { key: 'Ы', code: 'KeyY' },
                { key: 'В', code: 'KeyV' },
                { key: 'А', code: 'KeyA' },
                { key: 'П', code: 'KeyP' },
                { key: 'Р', code: 'KeyR' },
                { key: 'О', code: 'KeyO' },
                { key: 'Л', code: 'KeyL' },
                { key: 'Д', code: 'KeyD' },
                { key: 'Ж', code: 'Semicolon' },
                { key: 'Э', code: 'KeyE' },
            ],
            styles: 'repeat(11, 1fr)',
        },
        {
            keys: [
                { key: 'Shift', code: 'ShiftLeft' },
                { key: 'Я', code: 'KeyZ' },
                { key: 'Ч', code: 'KeyX' },
                { key: 'С', code: 'KeyS' },
                { key: 'М', code: 'KeyM' },
                { key: 'И', code: 'KeyI' },
                { key: 'Т', code: 'KeyT' },
                { key: 'Ь', code: 'KeyM' },
                { key: 'Б', code: 'KeyB' },
                { key: 'Ю', code: 'Period' },
                { key: 'Backspace', code: 'Backspace' },
            ],
            styles: 'repeat(11, 1fr)',
        },
        {
            keys: [
                { key: ',', code: 'NumpadDecimal' },
                { key: 'En', code: 190454634 },
                { key: 'Space', code: 'Space' },
                { key: '.', code: 'Period' },
                { key: 'Enter', code: 'Enter' },
            ],
            styles: '1.20fr 1.3fr 4fr 1.20fr 1.3fr',
        },
    ],
];
